title: Aren Warner # your name (or website title) here
logo: <img src="images/IMG_0867.JPG"/> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About me: 
  <br>I am a fourth year student at UMBC studying Geographic and Environmental Systems and GIS. Highlighted here are some recent projects for different classes and agencies I have done work for. While the projects described here are diverse, I specialize in fluvial systems and urban infrastructure.<br>
  <a href="https://www.linkedin.com/in/aren-warner/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
