title: Aren Warner # your name (or website title) here
logo: "images/IMG_2.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About me: 
  <br>I am a recent undergraduate of the University of Maryland, Baltimore County, with a Bachelor of Science in Geography and Environmental systems as well as a certificate in Applied GIScience. This page shows some of my undergraduate work learning and working with new tools such as Leaflet webmaps.<br>
  <a href="https://www.linkedin.com/in/aren-warner/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
